### ISSUE TITLE
NetworkInfo($ip, $port, $username, $password);

### ISSUE THREAD

**Issue by arulananth** [arzzen/altcoin-bitcoin-explorer#6]
How can get $ip,$port,$username,$password?

**Comment by arzzen** [comment]
hi @arulananth 
```
$ip = "localhost";
$port = 8332; // testnet 18332
$username = 'your_wallet_username';
$password = 'your_wallet_password';
```
you can read more info here https://bitcoin.org/en/developer-reference#remote-procedure-calls-rpcs

**Comment by arulananth** [comment]
Can you help me more? How to install Litecoin to my server set the username and password?

**Comment by arzzen** [comment]
if you have litecoin wallet, then you can connect to network and fetch network info

**Comment by arulananth** [comment]
I have litecoin wallet. I don't know how fetch the network info.
